# Generated by Django 6.0.1 on 2026-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_kategori_created_at_kategori_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(max_length=255),
        ),
    ]
